name: React Web Deployment

on:
    push:
        branches:
            - main

jobs:
    deploy-to-s3:
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: read
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  aws-region: us-east-1
                  role-to-assume: arn:aws:iam::058264200211:role/github_oidc
            - name: Install NPM packages
              run: npm install
            - name: Check Node Version
              run: node --version
            - name: Build Static Files
              run: npm run build
            - name: Remove previous web files
              run: aws s3 rm s3://event-n-greet-react-web/ --recursive
            - name: Upload new web files
              run: cd dist && aws s3 sync . s3://event-n-greet-react-web/
            - name: Invalidate Web CloudFront cache
              run: aws cloudfront create-invalidation --distribution-id E1DEIFIEABRIU6 --paths "/*"
